# Generated by Django 3.2.8 on 2021-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'draft'), ('TR', 'trash'), ('PB', 'published')], max_length=2)),
                ('imported_t', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(db_index=True, default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
                ('creator', models.TextField(default=None, null=True)),
                ('created_t', models.IntegerField(default=None, null=True)),
                ('created_datetime', models.DateTimeField(default=None, null=True)),
                ('last_modified_t', models.IntegerField(default=None, null=True)),
                ('last_modified_datetime', models.DateTimeField(default=None, null=True)),
                ('product_name', models.TextField(default=None, null=True)),
                ('generic_name', models.TextField(default=None, null=True)),
                ('quantity', models.TextField(default=None, null=True)),
            ],
        ),
    ]
